eEvent/urls.py
from django.contrib import admin
from django.urls import path, include
from event import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include("authorize.urls")),
    path('events/', include("event.urls")),
    path("", views.viewAllEvents, name="index"),
    path("__reload__/", include("django_browser_reload.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

event/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path("", views.viewAllEvents, name="event_index"),
    
    path("organizer/add/", views.AddEventOrganizer.as_view(), name="organizer_add_event"),
    path("organizer/", views.organizerEvents, name="organizer_events"),
    path("organizer/sells/", views.organizerSells, name="organizer_sells"),
    path("organizer/delete/<int:eid>/", views.deleteOrganizerEvent),
    path("organizer/<int:oid>/", views.viewOrganizerEventsById),
    path("organizer/discounts/", views.viewOrganizerDiscounts, name="organizer_discounts"),
    path("organizer/discount/delete/<int:did>/", views.deleteOrganizerDiscount),
    path("organizer/discount/edit/<int:did>/", views.EditDiscountOrganizer.as_view()),
    path("organizer/discount/add/", views.AddDiscount.as_view(), name="organizer_add_discount"),
    path("organizer/edit/<int:eid>/", views.EditEventOrganizer.as_view(), name="organizer_edit_discount"),
    
    path("attender/", views.AttenderEvents.as_view(), name="attender_events"),
    path("attender/<int:eid>/", views.AttenderEvents.as_view(), name="attender_events_post"),
    path("attender/pay/<int:eid>/", views.AttenderPayEvents.as_view()),
    path("<int:eid>/", views.viewEvent),
    path("search/", views.searchByTitle, name="search")
]

event/models.py
from django.utils import timezone
from django.db import models
from authorize.models import OrganizerUser, AttenderUser
from .managers import EventManager, DiscountManager

class Event(models.Model):
    title = models.TextField(max_length=100)
    description = models.TextField()
    location = models.TextField(max_length=200)
    price = models.DecimalField(decimal_places=2, max_digits=20)
    starts_on = models.DateTimeField()
    capacity = models.IntegerField()
    organizer_user = models.ForeignKey(OrganizerUser, on_delete=models.CASCADE)
    attender_users = models.ManyToManyField(AttenderUser, through='Attendance', related_name="events", blank=True)
    image = models.ImageField(upload_to="media")

    events = EventManager()

    def __str__(self):
        return self.title

    def is_valid(self):
        return True
     


class Attendance(models.Model):
    attender_user = models.ForeignKey(AttenderUser, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    paid = models.BooleanField(default=False)


class Discount(models.Model):
    title = models.TextField(max_length=100)
    code = models.TextField(max_length=10, unique=True)
    percentage = models.IntegerField()
    valid_until = models.DateTimeField()
    rate_limit = models.IntegerField()
    rate = models.IntegerField(default=0)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    organizer_user = models.ForeignKey(OrganizerUser, on_delete=models.CASCADE)

    discounts = DiscountManager()

    def is_valid(self):
        return timezone.now() < self.valid_until and self.rate < self.rate_limit

templates/menu.html
{% load static tailwind_tags %}

<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% tailwind_css %}
    {% block head %}
    
    {% endblock %}
</head>
<body dir="rtl" class="bg-gray-100 font-sans">
    <header class="w-full h-16 bg-gray-50 dark:bg-gray-900 text-white px-2 drop-shadow-lg sticky top-0">
        <div class="container px-4 md:px-0 h-full mx-auto flex justify-between items-center">
            <a href="{% url "index" %}" class="flex items-center">
                <img class="w-8 h-8 mr-2" src="{% static 'logo.svg' %}" alt="logo">
                <p>
                    مای کار
                </p>
            </a>
            <ul id="menu" class="hidden fixed top-0 right-0 px-10 py-16 bg-gray-800 z-50  md:relative md:flex md:p-0 md:bg-transparent md:flex-row md:space-x-6">
                <li class="md:hidden z-90 fixed top-4 right-6">
                    <a href="javascript:void (0)" class="text-right text-white text-4xl" onclick="toggleMenu()">× </a>
                </li>
                {% if not user.is_authenticated %}
                    <li><a class="text-white opacity-70 hover:opacity-100 duration-300" href="{% url "auth_login" %}">ورود/ثبت نام</a></li>
                {% else %}
                    <li><a class="text-white opacity-70 hover:opacity-100 duration-300" href="{% url "auth_logout" %}">خروج</a></li>
                {% endif %}
                <li><a class="text-white opacity-70 hover:opacity-100 duration-300" href="{% url "index" %}">قطعات</a></li>
                <li><a class="text-white opacity-70 hover:opacity-100 duration-300" href="https://www.rahvar120.ir/">پلیس</a></li>
                {% if perms.event.add_event %}
                    <li><a class="text-white opacity-70 hover:opacity-100 duration-300" href="{% url "organizer_add_event" %}">ایجاد قطعه</a></li>
                {% endif %}
                {% if perms.event.add_discount %}                
                    <li><a class="text-white opacity-70 hover:opacity-100 duration-300" href="{% url "organizer_add_discount" %}">ایجاد کد تخفیف</a></li>
                {% endif %}
                {% for group in request.user.groups.all  %}
                    {% if group.name == "AUTH_ORGANIZER" %}
                        <li><a class="text-white opacity-70 hover:opacity-100 duration-300" href="{% url "organizer_events" %}">قطعات شما</a></li>
                        <li><a class="text-white opacity-70 hover:opacity-100 duration-300" href="{% url "organizer_discounts" %}">کدهای تخفیف شما</a></li>
                        <li><a class="text-white opacity-70 hover:opacity-100 duration-300" href="{% url "organizer_sells" %}">لیست فروش</a></li>
                    {% endif %}
                    {% if group.name == "AUTH_ATTENDER" %}
                        <li><a class="text-white opacity-70 hover:opacity-100 duration-300" href="/events/attender/">لیست خرید</a></li>
                        <li><a class="text-white opacity-70 hover:opacity-100 duration-300" href="" onclick="showMessage()">کنترل کابین</a></li>
                        <li><a class="text-white opacity-70 hover:opacity-100 duration-300" href="" onclick="showMessage()">موقعیت</a></li>
                        <li><a class="text-white opacity-70 hover:opacity-100 duration-300" href="" onclick="showMessage()">سیستم ایمنی</a></li>
                        <li><a class="text-white opacity-70 hover:opacity-100 duration-300" href="" onclick="showMessage()">استارت از دور</a></li>
                        <li><a class="text-white opacity-70 hover:opacity-100 duration-300" href="" onclick="showMessage()">دریافت سرعت</a></li>
                        <li><a class="text-white opacity-70 hover:opacity-100 duration-300" href="{% url "index" %}">خرید قطعه</a></li>
                    {% endif %}  
                {% endfor %}
            </ul>
            <div class="flex items-center md:hidden">
                <button class="text-white text-4xl font-bold opacity-70 hover:opacity-100 duration-300" onclick="toggleMenu()"> ☰ </button>
            </div>
        </div>
    </header>
    <main>
        {% block main %}

        {% endblock %}
    </main>
    <script>
        var menu = document.getElementById('menu');
        function toggleMenu() {
            menu.classList.toggle('hidden');
            menu.classList.toggle('w-full');
            menu.classList.toggle('h-screen');
        }
        function showMessage(){
            alert('نیاز به اتصال به خودرو. برای اتصال به نمایندگی مراجعه کنید');
        }

    </script>
</body>
</html>